version: '3'  # версия docker-compose

services:  # контейнеры
  # контейнре db
  db:
    image: postgres:13.0-alpine # образ, из которого должен быть запущен контейнер
    volumes:  # директория для хранения данных
      - /var/lib/postgresql/data/
    env_file:  # # адрес файла, где хранятся переменные окружения
      - ./.env

  # контейнер django-проекта
  web:
    build: .  # директория Dockerfile
    restart: always  # аналог системы запуска юнитов в systemd
    volumes:
      # Контейнер web будет работать с данными, хранящиеся в томе static_value,
      # через свою директорию /app/static/
      - static_value:/app/static/
      # Данные, хранящиеся в томе media_value, будут доступны в контейнере web
      # через директорию /app/media/
      - media_value:/app/media/
    depends_on:  # после какого контейнера будет запущен этот
      - db
    env_file:  # # адрес файла, где хранятся переменные окружения
      - ./.env

  # контейнер nginx
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"  # запросы с внещнего порта 80 перенаправлять на внутрений 80

    volumes:
      # при сборке скопировать из ./nginx/default.conf
      # в контенйр и сохранить в /etc/nginx/conf.d/default.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

      # Контейнер nginx будет работать с данными, хранящиеся в томе static_value,
      # через свою директорию /var/html/static/
      - static_value:/var/html/static/
      # Данные, хранящиеся в томе media_value, будут доступны в контейнере nginx
      # через директорию /var/html/media/
      - media_value:/var/html/media/

    depends_on:
      - web

volumes:
  static_value:
  media_value:
