version: '3'  # версия docker-compose

services:  # контейнеры
  db:  # контейнре db
    image: postgres:13.0-alpine # образ, из которого должен быть запущен контейнер
    volumes:  # директория для хранения данных
      - /var/lib/postgresql/data/
    env_file:  # # адрес файла, где хранятся переменные окружения
      - ./.env
  web:  # контейнер django-проекта
    build: .  # директория Dockerfile
    restart: always  # аналог системы запуска юнитов в systemd
    ports:
     - "8000:8000"  # первый порт локальный, второй тот, что указал в dockerfile
    depends_on:  # после какого контейнера будет запущен этот
      - db
    env_file:  # # адрес файла, где хранятся переменные окружения
      - ./.env
